standard:
	g++ -std=c++11 -lrt -Wall -ggdb -o standard.exe main.cpp
	
standardgl:
	g++ -std=c++11 -Wall -ggdb -DGLFW_STATIC -o standardGL.exe standardGL.cpp -lglfw3 -lgdi32 -lglu32 -lopengl32 -IC:\Boost\
	
#-llibboost-timer.a -llibboost-chrono.a <- flags for boost libraries